# Generated by Django 3.2.9 on 2021-11-15 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('babystats', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='actiontype_text',
            new_name='event_text',
        ),
    ]
