# Generated by Django 3.2.9 on 2021-11-15 22:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('babystats', '0002_rename_actiontype_text_event_event_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 22, 13, 39, 262368, tzinfo=utc), verbose_name='Time started'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 15, 22, 13, 39, 262391, tzinfo=utc), verbose_name='Time ended'),
        ),
    ]
