# Generated by Django 3.2.9 on 2021-11-18 10:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('babystats', '0004_auto_20211115_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 10, 44, 8, 695013, tzinfo=utc), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 10, 44, 8, 726712, tzinfo=utc), verbose_name='Time started'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 10, 44, 8, 726737, tzinfo=utc), verbose_name='Time ended'),
        ),
    ]
