# Generated by Django 3.2.9 on 2021-11-18 10:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('babystats', '0005_auto_20211118_0544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 10, 45, 57, 666526, tzinfo=utc), verbose_name='Time started'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_to',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 18, 10, 45, 57, 666553, tzinfo=utc), verbose_name='Time ended'),
        ),
    ]
