# Generated by Django 3.2.9 on 2021-11-18 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('babystats', '0006_auto_20211118_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_from',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time started'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time_to',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Time ended'),
        ),
    ]
