# Generated by Django 3.2.9 on 2021-12-05 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babystats', '0007_auto_20211118_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='shit',
            field=models.BooleanField(default=False, verbose_name='Contains shit'),
        ),
    ]
