# Generated by Django 3.2.9 on 2021-12-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babystats', '0008_alter_event_shit'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='good_day',
            field=models.BooleanField(default=False, verbose_name='Had a good day?'),
        ),
    ]
